version: "3.8"
services:
  dev-db:
    image: postgres:15
    ports:
      - 3040:3040
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_DB: nest
      network: -freecodecamp
      
