PATCH http://localhost:3040/users
Content-Type: application/json


{
  // "firstName": "john",
  // "lastName": "adewale",   
  "age": 20,
  "email": "ade33333@gmail.com",    
  "password": "Pasdf1234$"        
}
