POST http://localhost:3040/users
Content-Type: application/json


{
    "firstName": "Emeka",
      "lastName": "Ibeka",
      "age": 28,
      "email": "emeka@mail.com",
      "password": "EmPass456@"
 }

POST http://localhost:3040/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoiZW1la2FAbWFpbC5jb20iLCJpYXQiOjE3NDY5MDE5NjUsImV4cCI6MTc0NjkwNTU2NSwiYXVkIjoibG9jYWxob3N0OjMwNDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzA0MCJ9._vtO0f1kSZagW2kjHPEKuG_yO1qzfAYKgMas6iniY0M

{
  "users": [
    {
      "firstName": "Amin",
      "lastName": "Yusu",
      "age": 30,
      "email": "ami@mail.com",
      "password": "StPass123!"
    },
    {
      "firstName": "Emeka",
      "lastName": "Ibeka",
      "age": 28,
      "email": "emeka@mail.com",
      "password": "EmPass456@"
    }
  ]
}
