POST http://localhost:3040/auth/refresh-token
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImVtYWlsIjoiZW1la2FAbWFpbC5jb20iLCJpYXQiOjE3NDcxNTY3NjIsImV4cCI6MTc0NzE2MDM2MiwiYXVkIjoibG9jYWxob3N0OjMwNDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzA0MCJ9.PCVAI1DXjaoEakVL_Yp4uNl0aqWPVlh3wm2gn3uRHRI


{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTc0NzE1Njc2MiwiZXhwIjoxNzQ3MjQzMTYyLCJhdWQiOiJsb2NhbGhvc3Q6MzA0MCIsImlzcyI6ImxvY2FsaG9zdDozMDQwIn0.VSiV3q-Un1u_ZYBLfMn9dNilW5eNzGifeGS_jwr23yM"
}